import { BrowserProvider, Contract, Interface, formatUnits, isAddress, parseUnits } from "https://cdn.jsdelivr.net/npm/ethers@6.13.4/+esm";

const CHAIN = { chainId: "0x1237", chainName: "Robinhood Chain", nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 }, rpcUrls: ["https://rpc.mainnet.chain.robinhood.com"], blockExplorerUrls: ["https://robinhoodchain.blockscout.com"] };
const HOODIE = "0xC72c01AAB5f5678dc1d6f5C6d2B417d91D402Ba3";
const factoryAbi = ["function createLauncher() returns (address)", "function launchersFor(address) view returns (address[])", "function HOODIE() view returns (address)"];
const launcherAbi = ["function launchToken(string name,string symbol,uint256 supply,uint256 initialTokenLiquidity,uint256 initialHoodieLiquidity,address recipient) returns (address,address)", "function launchCount() view returns (uint256)", "function launchAt(uint256) view returns (address token,address pool,address recipient,uint256 supply)", "event TokenLaunched(address indexed token,address indexed pair,address indexed tokenOwner,string name,string symbol,uint256 supply)"];
const poolAbi = ["function token() view returns (address)", "function hoodie() view returns (address)", "function reserveToken() view returns (uint256)", "function reserveHoodie() view returns (uint256)", "function totalSupply() view returns (uint256)", "function balanceOf(address) view returns (uint256)", "function initialized() view returns (bool)", "function addLiquidity(uint256,uint256,address) returns (uint256)", "function removeLiquidity(uint256,address) returns (uint256,uint256)", "function swapHoodieForToken(uint256,uint256,address) returns (uint256)", "function swapTokenForHoodie(uint256,uint256,address) returns (uint256)"];
const erc20Abi = ["function approve(address,uint256) returns (bool)"];
let provider, signer, account;
const $ = (id) => document.getElementById(id);
const toast = (text) => { $("toast").textContent = text; $("toast").classList.add("show"); setTimeout(() => $("toast").classList.remove("show"), 4200); };
const explorer = (hash) => `https://robinhoodchain.blockscout.com/tx/${hash}`;
const explorerAddress = (address) => `https://robinhoodchain.blockscout.com/address/${address}`;
const amountOut = (input, reserveIn, reserveOut) => { const inWithFee = input * 997n; return inWithFee * reserveOut / (reserveIn * 1000n + inWithFee); };
function factoryAddress(){ return $("factory").value.trim(); }
async function requireFactory(){
  const address = factoryAddress();
  if (!isAddress(address)) throw new Error("Enter a valid deployed factory address first.");
  if (!provider) throw new Error("Connect a wallet first.");
  if (await provider.getCode(address) === "0x") throw new Error("No contract is deployed at that factory address.");
  const factory = new Contract(address, factoryAbi, provider);
  if ((await factory.HOODIE()).toLowerCase() !== HOODIE.toLowerCase()) throw new Error("This factory is not bound to the required $HOODIE contract.");
  return address;
}
async function connect(){
  if (!window.ethereum) throw new Error("An EVM wallet such as Rabby, MetaMask, or Robinhood Wallet is required.");
  provider = new BrowserProvider(window.ethereum); await provider.send("eth_requestAccounts", []);
  try { await provider.send("wallet_switchEthereumChain", [{ chainId: CHAIN.chainId }]); } catch (e) { if (e.code === 4902) await provider.send("wallet_addEthereumChain", [CHAIN]); else throw e; }
  signer = await provider.getSigner(); account = await signer.getAddress(); $("connect").textContent = `${account.slice(0,6)}…${account.slice(-4)}`; toast("Wallet connected to Robinhood Chain.");
}
async function ensureWallet(){ if (!signer) await connect(); }
const sharedFactory = new URLSearchParams(window.location.search).get("factory");
$("factory").value = isAddress(sharedFactory || "") ? sharedFactory : (localStorage.getItem("hoodlaunch.factory") || "");
if (isAddress($("factory").value)) $("copyFactoryLink").hidden = false;
$("connect").onclick = () => connect().catch(e => toast(e.shortMessage || e.message));
$("saveFactory").onclick = async () => { try { await ensureWallet(); const address = await requireFactory(); localStorage.setItem("hoodlaunch.factory", address); const url = new URL(window.location.href); url.searchParams.set("factory", address); history.replaceState({}, "", url); $("copyFactoryLink").hidden = false; toast("Verified $HOODIE factory saved locally."); } catch(e) { toast(e.shortMessage || e.message); } };
$("copyFactoryLink").onclick = async () => { try { await navigator.clipboard.writeText(window.location.href); toast("Share link copied."); } catch { toast("Copy this app URL from your address bar."); } };
$("createLauncher").onclick = async () => { try { await ensureWallet(); const factory = new Contract(await requireFactory(), factoryAbi, signer); toast("Confirm launcher creation in your wallet…"); const tx = await factory.createLauncher(); $("launcherResult").innerHTML = `Creating… <a href="${explorer(tx.hash)}" target="_blank" rel="noreferrer">view transaction ↗</a>`; await tx.wait(); const launchers = await factory.launchersFor(account); const launcherAddress = launchers.at(-1); $("launcher").value = launcherAddress; $("launcherResult").innerHTML = `Launcher ready: <a href="${explorerAddress(launcherAddress)}" target="_blank" rel="noreferrer">${launcherAddress}</a>`; toast("Launcher created. It is permanently $HOODIE-only."); } catch(e) { toast(e.shortMessage || e.message); } };
$("loadHistory").onclick = async () => { try { await ensureWallet(); const launcherAddress = $("launcher").value.trim(); if (!isAddress(launcherAddress)) throw new Error("Enter a valid token launcher address below first."); const launcher = new Contract(launcherAddress, launcherAbi, provider); const count = await launcher.launchCount(); const start = count > 10n ? count - 10n : 0n; const records = []; for (let index = start; index < count; index++) records.push(await launcher.launchAt(index)); if (records.length === 0) { $("historyResult").textContent = "No tokens launched through this launcher yet."; return; } $("historyResult").innerHTML = records.reverse().map((record, offset) => `<p><b>#${Number(count) - offset}</b> <a href="${explorerAddress(record.token)}" target="_blank" rel="noreferrer">Token ↗</a> · <a href="${explorerAddress(record.pool)}" target="_blank" rel="noreferrer">$HOODIE pool ↗</a></p>`).join(""); } catch(e) { toast(e.shortMessage || e.message); } };
$("inspectPool").onclick = async () => { try { await ensureWallet(); const poolAddress = $("pool").value.trim(); if (!isAddress(poolAddress)) throw new Error("Enter a valid pool address."); const pool = new Contract(poolAddress, poolAbi, provider); const [token, hoodie, reserveToken, reserveHoodie, lpBalance, initialized] = await Promise.all([pool.token(), pool.hoodie(), pool.reserveToken(), pool.reserveHoodie(), pool.balanceOf(account), pool.initialized()]); if (!initialized || hoodie.toLowerCase() !== HOODIE.toLowerCase()) throw new Error("This is not an initialized HOOD//LAUNCH $HOODIE pool."); $("poolResult").innerHTML = `<p><b>Reserves</b><br>${formatUnits(reserveToken, 18)} token · ${formatUnits(reserveHoodie, 18)} $HOODIE</p><p><b>Your LP shares</b><br>${formatUnits(lpBalance, 18)}</p><p><a href="${explorerAddress(token)}" target="_blank" rel="noreferrer">Token ↗</a> · <a href="${explorerAddress(poolAddress)}" target="_blank" rel="noreferrer">Pool ↗</a></p>`; } catch(e) { toast(e.shortMessage || e.message); } };
$("quoteSwap").onclick = async () => { try { await ensureWallet(); const poolAddress = $("pool").value.trim(); if (!isAddress(poolAddress)) throw new Error("Enter a valid pool address first."); const rawSwap = $("swapAmount").value.trim(); if (!rawSwap || Number(rawSwap) <= 0) throw new Error("Enter a positive amount to quote."); const input = parseUnits(rawSwap, 18); if (input <= 0n) throw new Error("Enter an amount to quote."); const pool = new Contract(poolAddress, poolAbi, provider); const [hoodie, reserveToken, reserveHoodie, initialized] = await Promise.all([pool.hoodie(), pool.reserveToken(), pool.reserveHoodie(), pool.initialized()]); if (!initialized || hoodie.toLowerCase() !== HOODIE.toLowerCase()) throw new Error("This is not an initialized HOOD//LAUNCH $HOODIE pool."); const quote = $("swapDirection").value === "hoodie" ? amountOut(input, reserveHoodie, reserveToken) : amountOut(input, reserveToken, reserveHoodie); $("swapResult").textContent = `Current reserve quote: ${formatUnits(quote, 18)} output (before price movement). Set your own minimum output before swapping.`; } catch(e) { toast(e.shortMessage || e.message); } };
$("swap").onclick = async () => { try { await ensureWallet(); const poolAddress = $("pool").value.trim(); if (!isAddress(poolAddress)) throw new Error("Inspect or enter a valid pool address first."); const rawSwap = $("swapAmount").value.trim(); if (!rawSwap || Number(rawSwap) <= 0) throw new Error("Enter a positive amount to swap."); const pool = new Contract(poolAddress, poolAbi, signer); const [token, hoodie, initialized] = await Promise.all([pool.token(), pool.hoodie(), pool.initialized()]); if (!initialized || hoodie.toLowerCase() !== HOODIE.toLowerCase()) throw new Error("This is not an initialized HOOD//LAUNCH $HOODIE pool."); const amount = parseUnits(rawSwap, 18), minOut = parseUnits($("swapMinOut").value || "0", 18); const hoodieIn = $("swapDirection").value === "hoodie"; const inputToken = hoodieIn ? HOODIE : token; const asset = new Contract(inputToken, erc20Abi, signer); toast("Confirm token approval…"); await (await asset.approve(poolAddress, amount)).wait(); toast("Confirm swap…"); const tx = hoodieIn ? await pool.swapHoodieForToken(amount, minOut, account) : await pool.swapTokenForHoodie(amount, minOut, account); $("swapResult").innerHTML = `Swapping… <a href="${explorer(tx.hash)}" target="_blank" rel="noreferrer">view transaction ↗</a>`; await tx.wait(); $("swapResult").textContent = "Swap confirmed."; toast("Swap confirmed."); } catch(e) { toast(e.shortMessage || e.message); } };
$("quoteLiquidity").onclick = async () => { try { await ensureWallet(); const poolAddress = $("pool").value.trim(); if (!isAddress(poolAddress)) throw new Error("Enter a valid pool address first."); const tokenAmount = parseUnits($("addToken").value, 18); if (tokenAmount <= 0n) throw new Error("Enter a token liquidity amount first."); const pool = new Contract(poolAddress, poolAbi, provider); const [reserveToken, reserveHoodie, supply, initialized] = await Promise.all([pool.reserveToken(), pool.reserveHoodie(), pool.totalSupply(), pool.initialized()]); if (!initialized) throw new Error("Pool is not initialized."); const hoodieAmount = tokenAmount * reserveHoodie / reserveToken; const shares = tokenAmount * supply / reserveToken; $("addHoodie").value = formatUnits(hoodieAmount, 18); $("liquidityResult").textContent = `Matching liquidity filled in. Expected LP shares: ${formatUnits(shares, 18)}.`; } catch(e) { toast(e.shortMessage || e.message); } };
$("addLiquidity").onclick = async () => { try { await ensureWallet(); const poolAddress = $("pool").value.trim(); if (!isAddress(poolAddress)) throw new Error("Enter a valid pool address first."); const pool = new Contract(poolAddress, poolAbi, signer); const [token, hoodie, initialized] = await Promise.all([pool.token(), pool.hoodie(), pool.initialized()]); if (!initialized || hoodie.toLowerCase() !== HOODIE.toLowerCase()) throw new Error("This is not an initialized HOOD//LAUNCH $HOODIE pool."); const tokenAmount = parseUnits($("addToken").value, 18), hoodieAmount = parseUnits($("addHoodie").value, 18); toast("Confirm token approvals…"); await (await new Contract(token, erc20Abi, signer).approve(poolAddress, tokenAmount)).wait(); await (await new Contract(HOODIE, erc20Abi, signer).approve(poolAddress, hoodieAmount)).wait(); const tx = await pool.addLiquidity(tokenAmount, hoodieAmount, account); $("liquidityResult").innerHTML = `Adding liquidity… <a href="${explorer(tx.hash)}" target="_blank" rel="noreferrer">view transaction ↗</a>`; await tx.wait(); $("liquidityResult").textContent = "Liquidity added."; toast("Liquidity added."); } catch(e) { toast(e.shortMessage || e.message); } };
$("removeLiquidity").onclick = async () => { try { await ensureWallet(); const poolAddress = $("pool").value.trim(); if (!isAddress(poolAddress)) throw new Error("Enter a valid pool address first."); const shares = parseUnits($("removeShares").value, 18); const pool = new Contract(poolAddress, poolAbi, signer); const tx = await pool.removeLiquidity(shares, account); $("liquidityResult").innerHTML = `Removing liquidity… <a href="${explorer(tx.hash)}" target="_blank" rel="noreferrer">view transaction ↗</a>`; await tx.wait(); $("liquidityResult").textContent = "Liquidity removed."; toast("Liquidity removed."); } catch(e) { toast(e.shortMessage || e.message); } };
$("launchToken").onclick = async () => { try { await ensureWallet(); const launcherAddress = $("launcher").value.trim(); if (!isAddress(launcherAddress)) throw new Error("Enter a valid token launcher address."); const name = $("tokenName").value.trim(), symbol = $("tokenSymbol").value.trim(); if (!name || !symbol) throw new Error("Token name and ticker are required.");
  const supply = parseUnits($("supply").value, 18), tokenLiq = parseUnits($("tokenLiquidity").value, 18), hoodieLiq = parseUnits($("hoodieLiquidity").value, 18); if (tokenLiq >= supply) throw new Error("Pool token amount must be lower than total supply.");
  const hoodie = new Contract(HOODIE, erc20Abi, signer); toast("Confirm $HOODIE approval…"); const approval = await hoodie.approve(launcherAddress, hoodieLiq); await approval.wait();
  const launcher = new Contract(launcherAddress, launcherAbi, signer); toast("Confirm token launch…"); const tx = await launcher.launchToken(name, symbol, supply, tokenLiq, hoodieLiq, account); $("launchResult").innerHTML = `Launching pool… <a href="${explorer(tx.hash)}" target="_blank" rel="noreferrer">view transaction ↗</a>`; const receipt = await tx.wait(); const event = receipt.logs.map(log => { try { return launcher.interface.parseLog(log); } catch { return null; } }).find(Boolean); const tokenAddress = event.args.token, poolAddress = event.args.pair; $("pool").value = poolAddress; $("launchResult").innerHTML = `Live. <a href="${explorerAddress(tokenAddress)}" target="_blank" rel="noreferrer">Token ↗</a> · <a href="${explorerAddress(poolAddress)}" target="_blank" rel="noreferrer">$HOODIE pool ↗</a>`; toast("Token and funded $HOODIE pool launched.");
} catch(e) { toast(e.shortMessage || e.message); } };
