import { BrowserProvider, Contract, Interface, isAddress, parseUnits } from "https://cdn.jsdelivr.net/npm/ethers@6.13.4/+esm";

const HOODIE = "0xC72c01AAB5f5678dc1d6f5C6d2B417d91D402Ba3";
const CHAIN = { chainId:"0x1237", chainName:"Robinhood Chain", nativeCurrency:{name:"Ether",symbol:"ETH",decimals:18}, rpcUrls:["https://rpc.mainnet.chain.robinhood.com"], blockExplorerUrls:["https://robinhoodchain.blockscout.com"] };
const factoryAbi = ["function createLauncher() returns (address)","function launchersFor(address) view returns (address[])","function HOODIE() view returns (address)"];
const launcherAbi = ["function launchToken(string,string,uint256,uint256,uint256,address) returns (address,address)","event TokenLaunched(address indexed token,address indexed pair,address indexed tokenOwner,string name,string symbol,uint256 supply)"];
const erc20Abi = ["function approve(address,uint256) returns (bool)"];
const $ = id => document.getElementById(id); let provider, signer, account, launcherAddress;
const toast = text => { $("toast").textContent=text; $("toast").classList.add("show"); setTimeout(()=>$("toast").classList.remove("show"),4000); };
const txUrl = hash => `https://robinhoodchain.blockscout.com/tx/${hash}`;
const factoryAddress = () => window.HOODIEPAD_FACTORY_ADDRESS || new URLSearchParams(location.search).get("factory") || "";
async function wallet(){ if(signer)return; if(!window.ethereum)throw new Error("Connect an EVM wallet to continue."); provider=new BrowserProvider(window.ethereum); await provider.send("eth_requestAccounts",[]); try{await provider.send("wallet_switchEthereumChain",[{chainId:CHAIN.chainId}]);}catch(e){if(e.code===4902)await provider.send("wallet_addEthereumChain",[CHAIN]);else throw e;} signer=await provider.getSigner();account=await signer.getAddress();$("connect").textContent=`${account.slice(0,6)}…${account.slice(-4)}`; await restoreLauncher(); }
async function factory(){ const address=factoryAddress(); if(!isAddress(address))throw new Error("HoodiePad is not configured yet. Add the deployed factory address in app/config.js."); const c=new Contract(address,factoryAbi,signer||provider); if((await c.HOODIE()).toLowerCase()!==HOODIE.toLowerCase())throw new Error("This is not the verified $HOODIE HoodiePad factory."); return c; }
async function restoreLauncher(){ const saved=localStorage.getItem("hoodiepad.launcher"); if(isAddress(saved||"")) launcherAddress=saved; try{const launchers=await (await factory()).launchersFor(account); if(launchers.length) launcherAddress=launchers.at(-1);}catch{} if(launcherAddress){localStorage.setItem("hoodiepad.launcher",launcherAddress);$("tokenPanel").classList.remove("locked");$("tokenStep").classList.add("active");$("launcherResult").textContent="Your existing launcher is ready to use.";} }
$("connect").onclick=()=>wallet().then(()=>toast("Wallet connected.")).catch(e=>toast(e.shortMessage||e.message));
$("createLauncher").onclick=async()=>{try{await wallet();const c=await factory();toast("Confirm creation in your wallet…");const tx=await c.createLauncher();$("launcherResult").innerHTML=`Creating your launcher… <a href="${txUrl(tx.hash)}" target="_blank">view ↗</a>`;await tx.wait();launcherAddress=(await c.launchersFor(account)).at(-1);localStorage.setItem("hoodiepad.launcher",launcherAddress);$("launcherResult").textContent="Your launcher is ready. Now launch its first token.";$("tokenPanel").classList.remove("locked");$("tokenStep").classList.add("active");toast("Launcher created.");}catch(e){toast(e.shortMessage||e.message);}};
$("launchToken").onclick=async()=>{try{await wallet();if(!launcherAddress)throw new Error("Create your launcher first.");const name=$("tokenName").value.trim(),symbol=$("tokenSymbol").value.trim(),hoodieRaw=$("hoodieLiquidity").value.trim();if(!name||!symbol||!hoodieRaw)throw new Error("Add a name, ticker, and $HOODIE liquidity amount.");const supply=parseUnits($("supply").value,18),tokenLiq=parseUnits($("tokenLiquidity").value,18),hoodieLiq=parseUnits(hoodieRaw,18);if(tokenLiq>=supply)throw new Error("Liquidity tokens must be lower than total supply.");toast("Step 1 of 2: approve $HOODIE…");await (await new Contract(HOODIE,erc20Abi,signer).approve(launcherAddress,hoodieLiq)).wait();toast("Step 2 of 2: launch token…");const l=new Contract(launcherAddress,launcherAbi,signer),tx=await l.launchToken(name,symbol,supply,tokenLiq,hoodieLiq,account);$("launchResult").innerHTML=`Launching… <a href="${txUrl(tx.hash)}" target="_blank">view ↗</a>`;const receipt=await tx.wait();const event=receipt.logs.map(x=>{try{return l.interface.parseLog(x)}catch{return null}}).find(event=>event?.name==="TokenLaunched");if(!event){$("launchResult").innerHTML=`Token launch confirmed. <a href="${txUrl(tx.hash)}" target="_blank">View transaction ↗</a>`;toast("Token launch confirmed.");return;}$("launchResult").innerHTML=`<b>${name} is live.</b> Token: ${event.args.token} · $HOODIE pool: ${event.args.pair}`;toast("Your token is live.");}catch(e){toast(e.shortMessage||e.message);}};
